In [1]:
import numpy as np

In [3]:
a = np.random.randint(30,99,20)
a

array([77, 57, 86, 78, 54, 73, 58, 72, 73, 49, 85, 67, 39, 35, 55, 90, 58,
       42, 97, 30])

In [4]:
a[-1]

30

In [5]:
a[4]

54

In [6]:
a.ndim

1

In [9]:
b= np.random.randint(20,80,(8,9))
b

array([[45, 33, 71, 41, 61, 76, 72, 54, 36],
       [61, 35, 25, 55, 32, 68, 42, 67, 45],
       [39, 61, 26, 59, 68, 68, 61, 60, 73],
       [41, 20, 63, 40, 21, 28, 53, 46, 42],
       [67, 52, 49, 29, 43, 40, 75, 21, 26],
       [45, 60, 25, 22, 39, 28, 36, 59, 67],
       [20, 47, 71, 62, 29, 25, 59, 68, 62],
       [65, 48, 64, 32, 54, 47, 25, 58, 71]])

In [10]:
b.shape

(8, 9)

In [12]:
b[1:5,1:6]

array([[35, 25, 55, 32, 68],
       [61, 26, 59, 68, 68],
       [20, 63, 40, 21, 28],
       [52, 49, 29, 43, 40]])

In [13]:
import pandas as pd


In [17]:
k = [[4,7],[2,9],[7,3],[90,50]]
k

[[4, 7], [2, 9], [7, 3], [90, 50]]

In [19]:
t =np.array(k)
t

array([[ 4,  7],
       [ 2,  9],
       [ 7,  3],
       [90, 50]])

In [20]:
t.shape

(4, 2)

In [21]:
pd.Series(k)

0      [4, 7]
1      [2, 9]
2      [7, 3]
3    [90, 50]
dtype: object

In [24]:
pd.DataFrame(t)

0   1
0   4   7
1   2   9
2   7   3
3  90  50

In [27]:
 df = pd.DataFrame(t,columns = ['name','sub' ], index = [289,290,291,292])
 df

name  sub
289     4    7
290     2    9
291     7    3
292    90   50

In [28]:
df.columns

Index(['name', 'sub'], dtype='object')

In [30]:
df['sub'].mean()

17.25

In [32]:
df['sub'].median()

8.0

In [33]:
df['sub'].var()

482.9166666666667

In [34]:
df['sub'].std()

21.975364995072702

In [35]:
df['sub'].min()

3

In [36]:
df['sub'].max()

50

In [37]:
df['sub'].quantile(0.25)

6.0

In [38]:
df['sub'].quantile(0.5)

8.0